name: DevSecOps Secure SDLC Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  sast_scan:
    name: Run SAST (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Run Semgrep
        # We tell Semgrep to save findings to a file, but continue the pipeline so we can upload it
        run: |
          pip install semgrep
          semgrep scan --config=auto --json -o semgrep-sast-report.json || true

      - name: Upload SAST Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sast-report
          path: semgrep-sast-report.json

  sca_scan:
    name: Run SCA (Snyk)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Application Dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Run Snyk and Generate Report
        # We use '|| true' so the pipeline completes and allows us to save the report artifact
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npx snyk test --severity-threshold=high --json-file-output=snyk-sca-report.json || true

      - name: Upload SCA Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sca-report
          path: snyk-sca-report.json
